Handle empty department contact
The build was failing due to something like

```
TypeError: Cannot read property 'name' of undefined

    at Contact (/app/dist/static.288553d5.js:1578:22)
```

We need to account for empty contacts